version: "3"

services:
  php-nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/www.conf:/etc/php-fpm.d/www.conf

    image: trang-le-nginx-php
    ports:
      - "8080:80"
    networks:
      - internal
  postgres_db:
    image: postgres:latest
    hostname: postgres-db
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d/
networks:
  internal:
    driver: bridge
