version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
    image: trang-le-nginx-php
    ports:
      - "8080:80"
    networks:
      - internal
networks:
  internal:
    driver: bridge
